apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: kselect-demo
type: Opaque
stringData:
  username: admin
  password: s3cur3-passw0rd
  host: db.example.com
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  namespace: kselect-demo
type: Opaque
stringData:
  stripe-key: sk_test_demo123
  sendgrid-key: SG.demo456
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: kselect-demo
type: kubernetes.io/tls
data:
  # dummy self-signed cert (base64)
  tls.crt: LS0tLS1CRUdJTi0tLS0tCk1JSUI9RENDQVZ1Z0F3SUJBZ0lKQUx6WUNMVE0K
  tls.key: LS0tLS1CRUdJTi0tLS0tCk1JSUI5VENDQVZ1Z0F3SUJBZ0lKQUx6WUNMVE0K
