apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: kselect-demo
  labels:
    app: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: kselect-demo
  labels:
    app: worker
